os: osx
osx_image: xcode10

# Remove things Strap installs (so we can test installing them from scratch).
before_script:
  - travis_wait sudo rm -rf /usr/local/bin/brew /usr/local/.??* /Applications/Xcode.app /Library/Developer/CommandLineTools /usr/local/Caskroom
  - sudo pkgutil --forget com.apple.pkg.CLTools_Executables

# Check the syntax of the shell script.
script:
  - brew install shellcheck
  - shellcheck bin/strap.sh
