os: osx
osx_image: xcode10

install:
  # Install testing dependencies.
  - npm -g install ejs-cli
  - brew install bats-core shellcheck

  # Remove Homebrew, Xcode and Command Line Tools.
  - travis_wait sudo rm -rf /usr/local/bin/brew /usr/local/.??* /Applications/Xcode.app /Library/Developer/CommandLineTools /usr/local/Caskroom
  - sudo pkgutil --forget com.apple.pkg.CLTools_Executables

script:
  # Lint shell scripts (exclude warnings: `unrecognized shebang` [SC1008], `@test literal {}` [SC1083 + SC1089]).
  - shellcheck --exclude SC1008,SC1083,SC1089 bin/*.sh test/*.sh

  # Run tests.
  - travis_wait test/strap.test.sh
